var modules =
[
    [ "adhoc", "group__adhoc.html", "group__adhoc" ],
    [ "battery", "group__batt.html", "group__batt" ],
    [ "buttons", "group__buttons.html", "group__buttons" ],
    [ "cam", "group__cam.html", "group__cam" ],
    [ "channel", "group__channel.html", "group__channel" ],
    [ "color", "group__color.html", "group__color" ],
    [ "console", "group__console.html", "group__console" ],
    [ "draw", "group__draw.html", "group__draw" ],
    [ "files", "group__files.html", "group__files" ],
    [ "font", "group__font.html", "group__font" ],
    [ "ftp", "group__ftp.html", "group__ftp" ],
    [ "game", "group__game.html", "group__game" ],
    [ "hardware", "group__hardware.html", "group__hardware" ],
    [ "http", "group__http.html", "group__http" ],
    [ "image", "group__image.html", "group__image" ],
    [ "ini", "group__ini.html", "group__ini" ],
    [ "link", "group__link.html", "group__link" ],
    [ "maps", "group__maps.html", "group__maps" ],
    [ "math", "group__math.html", "group__math" ],
    [ "motion", "group__motion.html", "group__motion" ],
    [ "os", "group__os.html", "group__os" ],
    [ "osk", "group__osk.html", "group__osk" ],
    [ "power", "group__power.html", "group__power" ],
    [ "screen", "group__screen.html", "group__screen" ],
    [ "socket", "group__socket.html", "group__socket" ],
    [ "sound", "group__sound.html", "group__sound" ],
    [ "splash", "group__splash.html", "group__splash" ],
    [ "themes", "group__themes.html", "group__themes" ],
    [ "thread", "group__thread.html", "group__thread" ],
    [ "timers", "group__timers.html", "group__timers" ],
    [ "touch", "group__touch.html", "group__touch" ],
    [ "wlan", "group__wlan.html", "group__wlan" ]
];
